### ISSUE TITLE
Error in Program Execution

### ISSUE THREAD

**Issue by ucarseyhan** [ManiAm/VENTOS_Public#1]
Dear Maniam;

First of all, thank you for detailed explanation of installation of VENTOS. I successfully follow your step and install VENTOS on my computer (Ubuntu 14.04). However, when I try to run the simulation with the following configuration, I got error;
Config: params2_CACC.ini, CACCVehicleStream1 (Also I cannot find the params_config.ini file in the IDE  may be I misunderstood something).

I think the error is related with SUMO  and the log of SUMO is below(I cannot attach file permission is denied.)

DEBUG:root:Logging to /tmp/sumo-launchd.log
INFO:root:Listening on port 9999
DEBUG:root:Connection from 127.0.0.1 on port 53050
DEBUG:root:Handling connection from 127.0.0.1 on port 53050
DEBUG:root:Got TraCI message of length 2
DEBUG:root:Got TraCI command of length 1
DEBUG:root:Got TraCI command 0x0
DEBUG:root:Got CMD_GETVERSION
DEBUG:root:Got TraCI message of length 328
DEBUG:root:Got TraCI command of length 323
DEBUG:root:Got TraCI command 0x75
DEBUG:root:Got CMD_FILE_SEND for "sumo-launchd.launch.xml"
DEBUG:root:Got CMD_FILE_SEND with data "<launch>
	<copy file="3hello.net.xml"/>
	<copy file="4hello.rou.xml"/>
	<copy file="5hello.loopDetector.xml"/>
	<copy file="gui-settings.cfg"/>
	<copy file="6hello.sumo.cfg" type="config"/>
	<basedir path="/home/seyhan/Desktop/VENTOS/VENTOS/sumo/CACC_Stream"/>
	<seed value="0"/>
</launch>

"
DEBUG:root:Creating temporary directory...
DEBUG:root:Temporary dir is /tmp/sumo-launchd-tmp-XDsPeJ
DEBUG:root:Base dir is /home/seyhan/Desktop/VENTOS/VENTOS/sumo/CACC_Stream
DEBUG:root:Seed is 0
DEBUG:root:Finding free port number...
DEBUG:root:Claiming lock on port
DEBUG:root:...found port 42347
INFO:root:Starting SUMO (/home/seyhan/Desktop/VENTOS/VENTOS/sumoBinary/sumo-guiD -c 6hello.sumo.cfg) on port 42347, seed 0
DEBUG:root:Connecting to SUMO (/home/seyhan/Desktop/VENTOS/VENTOS/sumoBinary/sumo-guiD -c 6hello.sumo.cfg) on port 42347 (try 1)
DEBUG:root:Error ([Errno 111] Connection refused)
DEBUG:root:Connecting to SUMO (/home/seyhan/Desktop/VENTOS/VENTOS/sumoBinary/sumo-guiD -c 6hello.sumo.cfg) on port 42347 (try 2)
DEBUG:root:Releasing lock on port
DEBUG:root:Starting proxy mode
DEBUG:root:Done with proxy mode
DEBUG:root:Done with proxy mode, killing SUMO
DEBUG:root:SIGTERM
INFO:root:Done running SUMO
DEBUG:root:Cleaning up
DEBUG:root:Result: "<?xml version="1.0"?>
<status>
	<exit-code>-15</exit-code>
	<start>1446974456</start>
	<end>1446974460</end>
	<status>Exited with error code -15</status>
	<stdout><![CDATA[Loading configuration... done.
]]></stdout>
	<stderr><![CDATA[]]></stderr>
</status>
"
DEBUG:root:Closing connection from 127.0.0.1 on port 53050
WARNING:root:Keyboard interrupt.
INFO:root:Shutting down.

Regards.

**Comment by ManiAm** [comment]
1. You can ignore the params_config.ini since its an old file name.

2. I have attached the logging output for the same scenario on my machine

![mani mani-thinkpad-t430s _002](https://cloud.githubusercontent.com/assets/5473998/11019761/9e9197fa-85bc-11e5-90a6-455afa2a7042.png)

- can you check the sumoBinary folder to make sure the SUMO binaries are there?
- note that you can not use the official sumo binaries. We have modified the binaries and they will be downloaded upon first execution automatically into the sumoBinary folder.
If its not there, download the sumoD and sumoguiD from the following link:

https://www.dropbox.com/sh/uab52dnqteozw26/AAAaMUDGqWVL7BKOqM29xXx2a?dl=0

- one part of the logging is missing for you. The part that shows the content of launchd file.

**Comment by ucarseyhan** [comment]
Dear Maniam;

As you direct in ReadMe file, when I execute the simulation first, the modified sumo binaries are downloaded. Also I checked  from the IDE project explorer. However, still when I execute the 
simulation and press the SUMO start simulation button, I got an error and simulation is terminated.

Regards.

**Comment by ucarseyhan** [comment]
Dear Maniam;

One additional comment is;  when I run the simulation with ini file params2_CACC.ini and 
config name TrafficDemand everything works fine. I can see the vehicles on SUMO windows.
Do you have any suggestion to me?

Regards.

**Comment by ManiAm** [comment]
I double checked all scenario and they are all working fine! 

Its hard to find which part of the code is causing the problem.
can you run the scenario in debug mode to detect the problematic part?
right-click on the params2_CACC.ini and click Debug as.
The debugger should stop right before the problematic line.

**Comment by ucarseyhan** [comment]
Dear Maniam;

I reinstall my ubuntu 14.04 and follow your steps. However, I get stuck in the same position. My simulation ends with same error. (however works in params2_CACC.ini and  config name TrafficDemand ) As you suggest, I debug the scenario and the error generated is below;

Can't find a source file at "/build/buildd/eglibc-2.19/libio/iofclose.c" 
Locate the file or edit the source lookup path to include its location.

Regards.

**Comment by ManiAm** [comment]
I think I found the bug! Please pull to get the latest code and re-run your code. Let me know if the problem is solved!

**Comment by ucarseyhan** [comment]
Dear ManiAm;

After starting from scratch, I got an error when I try to build VENTOS. The IDE generated error is below;

TraCI_App.cc
In file included from TraCI_App.h:31:0,
                 from TraCI_App.cc:28:
TraCI_Extend.h:38:24: fatal error: rapidxml.hpp: No such file or directory
 #include <rapidxml.hpp>
                        ^
compilation terminated.
make[2]: Leaving directory `/home/su/Desktop/PlatoonSimulation/VENTOS/application/traci'
make[1]: Leaving directory `/home/su/Desktop/PlatoonSimulation/VENTOS/application'
make[2]: *** [../../out/gcc-debug/application/traci/TraCI_App.o] Error 1
make[1]: *** [traci_dir] Error 2
make: *** [application_dir] Error 2

Regards.

**Comment by ucarseyhan** [comment]
Dear ManiAM;

After the last update, the simulation platform works. The error I think you correct is related VENTOS and VENTOS_Public. Thanks for your help and interest.

Regards.

**Comment by santamaiti** [comment]
Hi ManiAM,

The steps are really helpful. Everything worked fine for me. Only in last part, when I run sumo, it's throwing a runtime error. Could you please suggest.
<status>
	<exit-code>-1</exit-code>
	<start>1452387204</start>
	<end>1452387204</end>
	<status>Could not start SUMO (/home/santa/Desktop/workspace/VENTOS_Public/sumoBinary/sumo-guiD -c 6hello.sumo.cfg): [Errno 8] Exec format error</status>
	<stdout><![CDATA[]]></stdout>
	<stderr><![CDATA[]]></stderr>
</status>

Regards,
