### ISSUE TITLE
check collision rate

### ISSUE THREAD

**Issue by 93paulleee** [ManiAm/VENTOS_Public#12]
Thanks for your work.

i have more question about collision rate.

in nic/phy/module.ned , turn 'true' emulation option.

but there is no count 'Data/Packet Collision' . What Can i do?

**Comment by ManiAm** [comment]
In the latest example that I have added into VENTOS, you can see the frame collision. check Section 17.1 of the new manual and get the latest code as I mentioned in my last answer.
