### ISSUE TITLE
Clustering Problem

### ISSUE THREAD

**Issue by 93paulleee** [ManiAm/VENTOS_Public#13]
i want make Vehicle Clustering, how can i make it?

does VENTOS support Vehicle Clustering?

**Comment by ManiAm** [comment]
Can you elaborate more on what do you mean by a vehicle cluster? If you mean a vehicle platoon (check link below), then the answer is yes. Go to examples/platoon_cacc and open the omnetpp.ini file. The first configuration (CACCVehicleStream1) shows you a simple platooning scenario. Have a look at section 3.7: 'Adding vehicle platoon' and section 4.3: 'platoon coordination'.

Vehicle platoon: 
https://en.wikipedia.org/wiki/Platoon_(automobile)

**Comment by 93paulleee** [comment]
First of all, Thanks for your work. i'm really appreciate it.
this time, i will ask just 2 Things.

<1. Transmission power and Transmission Range>
how can i Change Transmision Range in Vehicle  using Transmission power?

<2. about Vehicle Cluster(Group)>
I mean Cluster is Grouping.
I saw the Platoon_CACC code and running motion. i Think the platoon code is already make group. i want make group just step by step.
i need variable Group.  there is no group in standard communication.

now i'm trying to make a Vehicle Group.
my algorithm is here.
1. check collision rate is rsu
2. if ( collision rate >= Threshold) --> go to Group
3. in Group, Group Member change the Transmission range (Change it's TxPower to reduce Transmission range)
4. Group Member communication with just Group Member and Group Leader
5. Group Master(Group Leader) Communication with other Group Leader and RSU
The VENTOS support these things?

Thank you for the help.
after my work is done, i wanna donate for your group.
