### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by xwenarthur** [ManiAm/VENTOS_Public#23]
Hi Mani

I'm really sorry to disturb you. I'm a graduate from US. Now I got an installation problem. When I run './runme', a configure error generates, as the figure shows.
<img width="737" alt="screen shot 2018-04-17 at 15 33 13" src="https://user-images.githubusercontent.com/38415976/38902365-139751e6-4255-11e8-93b5-da846c56587c.png">
I'm confused because I'm sure I installed osgearth package.

If I set 'WITH_OSGEARTH=no' in configure.user, there is another error shown below.
<img width="727" alt="screen shot 2018-04-17 at 15 27 24" src="https://user-images.githubusercontent.com/38415976/38902434-528dacd8-4255-11e8-96aa-3713dfd470cd.png">

What should I do? I really need your help. Because this's my graduation thesis. :)

Thank you!

**Comment by ManiAm** [comment]
>> If I set 'WITH_OSGEARTH=no' in configure.user, there is another error shown below.

you should not use that flag, because osgearth lib is needed during compile time.


What version of Ubuntu are you running? 16.04?

**Comment by xwenarthur** [comment]
Yes. I use Ubuntu 16.04

**Comment by ManiAm** [comment]
can you run this command in terminal and tell me the output?

`echo $PATH`

**Comment by xwenarthur** [comment]
Sure! Thank you for your time.
<img width="1003" alt="screen shot 2018-04-17 at 17 10 00" src="https://user-images.githubusercontent.com/38415976/38904946-31a87130-4262-11e8-8d23-414ffb472e5a.png">

**Comment by ManiAm** [comment]
Also this:

dpkg -l '*osg*'

**Comment by xwenarthur** [comment]
<img width="906" alt="screen shot 2018-04-17 at 21 28 20" src="https://user-images.githubusercontent.com/38415976/38911762-470f914c-4286-11e8-8029-4d07219b3597.png">
Here is it.

**Comment by ManiAm** [comment]
it is identical to my system. The error you get is from the g++ compiler itself! Notice that the error says internal error!

I suggest you to go to the omnet directory from the terminal and run `make clean` to clean the build and then run `make all`. Then run the runme script again.

**Comment by xwenarthur** [comment]
Thank you!
I did it but another problem shows up. It seems 'Makefile.inc' doesn't exist. There is only a file called 'Makefile.inc.in', as the figure shows.

<img width="1382" alt="screen shot 2018-04-17 at 21 43 32" src="https://user-images.githubusercontent.com/38415976/38912298-5a7ea2a6-4289-11e8-9b63-73fb54583d54.png">

**Comment by ManiAm** [comment]
I thought that the runme script has run the configure command for you first. Run these:

`./configure`
`make`

**Comment by xwenarthur** [comment]
When I go to the omnet directory and type in:
./configure
make

It still says 'configure: error: Cannot find osgEarth......'

Makefile:36: Makefile.inc: No such file or directory
make: *** No rule to make target 'Makefile.inc'.  Stop.

I have even deleted the Ubuntu and re-installed it. But it still happens... :(
<img width="1057" alt="screen shot 2018-04-17 at 22 36 36" src="https://user-images.githubusercontent.com/38415976/38913581-5e2e80c2-4290-11e8-92bc-7ddd4b5b02ac.png">

**Comment by ManiAm** [comment]
this is very strange! unfortunately I do not have any more hints for you. I even installed VENTOS from scratch on a fresh Ubuntu and it worked! I suggest you to download OMNET from their official website and follow their installation guide to install it on Ubuntu and then import VENTOS.

**Comment by xwenarthur** [comment]
Ok. Btw, should I install OMNET 5.0 or 5.1?

Thank you!

**Comment by ManiAm** [comment]
OMNET 5.1:

https://www.omnetpp.org/component/jdownloads/download/32-release-older-versions/2309-omnetpp-5-1-linux

**Comment by xwenarthur** [comment]
Thank you Mani.
Now I'm able to install VENTOS on my mac. The trick is that the VirtualBox, not Parallel Desktop should be used.

But now I got another problem. When running the sample scenario as the figure shows, is there any idea?
<img width="1021" alt="screen shot 2018-04-19 at 00 09 26" src="https://user-images.githubusercontent.com/38415976/38976388-1a149e86-4366-11e8-82d1-9e3aa8c52012.png">

**Comment by ManiAm** [comment]
>> The trick is that the VirtualBox, not Parallel Desktop should be used.

I though that you are already using VirtualBox or VMWare. I am not familiar with parallel desktop.

>> But now I got another problem, when running the sample scenario. Is there any idea?

Your run configuration is wrong! The working dir should point to a folder in the example folder (platoon_cacc) and ini file(s) should be omnetpp.ini in your example.

**Comment by xwenarthur** [comment]
Thank you a lot, Mani!!!

Finally, I'm able to run the simulation scenario! :)

**Comment by ManiAm** [comment]
Good! i am closing this issue.
