### ISSUE TITLE
General Program Execution

### ISSUE THREAD

**Issue by ucarseyhan** [ManiAm/VENTOS_Public#3]
Dear ManiAm;

First, thank you for opening this simulation platform as open source. I am writing to get more information regarding your platform VENTOS. The findings that I gather from your code are as follows;

* You have 3 type of platoon scenarios namely, platoonOff, platoonFormed and platoonManagement. For these, you create different .cc and .h files for example ApplV_05_PlatoonFormed.h  ApplV_05_PlatoonFormed.cc  for platoonFormed scenario.
* Adversary vehicle behaviour is implemented on files ApplAdversary.h and ApplAdversary.cc
* The simulation can be configured via altering the params. ini file. For example params_CACC.ini has five sections where section 4 is for platoon already formed.

My first question is related to the adversary vehicle and its behaviour.  Adversary vehicle can be configured in params1_General.ini file in Section 12: Adversary Parameters.  Is it enough to set true one of the following for deciding adversary behaviour? (adversary related information is in ApplAdversary.cc)

Network.adversary[*].appl.falsificationAttack = false
Network.adversary[*].appl.replayAttack = false 
Network.adversary[*].appl.jammingAttack = false  

My second question is related with the platoon formed scenarios. The adversary vehicle can be added to platoon via changing the addAdversary.on parameters. But, I am a little bit confused about the platoon formed scenario. Is there any adversary vehicle on this scenario? Or how I can add one adversary vehicle into formed platoon? Is it possible to set the vehicle that is in platoon depth 1 as an adversary?

Thanks for your help.
Kind regards.

**Comment by ManiAm** [comment]
> Adversary vehicle can be configured in params1_General.ini file in Section 12: Adversary Parameters. 

Do not use the general parameters defined in params1_General.ini otherwise other scenarios might also get affected. The correct configure for adversary is in file params4_Other.ini under the name Config Adversary.

> Is it enough to set true one of the following for deciding adversary behavior? (adversary related information is in ApplAdversary.cc)

As I mentioned above, you can find a working scenario in  params4_Other.ini file under the name Config Adversary. Try to turn on one attack at a time.


> My second question is related with the platoon formed scenarios. The adversary vehicle can be added to platoon via changing the addAdversary.on parameters. But, I am a little bit confused about the platoon formed scenario. Is there any adversary vehicle on this scenario? Or how I can add one adversary vehicle into formed platoon? Is it possible to set the vehicle that is in platoon depth 1 as an adversary?

If you run the scenario, you can see that the adversary is sitting beside the road and broadcasts faulty messages. You can make one of the vehicles as adversary by changing the code.

**Comment by ucarseyhan** [comment]
Dear Maniam;

Thanks for your previous explanation. It was really helpful to me. Now, I am writing yo ask the general structure of your simulator VENTOS. Sorry for lots of question. The questions are below

1-If I think the VENTOS from the top-down structure, then ApplV_Manager is the top class. ( Fig.1 in your platoon management with cooperative... paper) Am I right? So when a vehicle receives platoon msg, you call onData function and the working responsibility is delegated to lower later. For example, onBeaconVehicle: first  ApplVCoordinator::onBeaconVehicle(wsm); is called then based on the platoon depth, VENTOS applies control parameters.

2- The scenario that I use is related to the params2_CACC.ini and section 4 where the platoon has already formed. The speed profile of this scenario is set to 3. What are the minimum and maximum speed values of this mode? Is it possible to set min, max, and normal speed?

3-I need a function that gives me the vehicle's front platoon member and rear platoon member. From the Traci_Extend, is there any method  that implements this functionality? Or how a platoon member know the front and the rear platoon member in the platoon?

Thanks for your attention.
Regards.

**Comment by anika0625** [comment]
Hello

I am facing some issues during compilation of ventos project.
Error Details is:
SumoServer.cc:39:27: error: ‘simulation’ was not declared in this scope
         cModule *module = simulation.getSystemModule()->getSubmodule("SumoBinary");

I am getting this error. Please assist me how can i resolve it.

I have another query Can I run ventos simulator on two laptops simultaneously so that communication between two can be possible??? 

Please provide the solution for these two queries.  
                           ^

**Comment by ManiAm** [comment]
> 1-If I think the VENTOS from the top-down structure, then ApplV_Manager is the top class. ( Fig.1 in your platoon management with cooperative... paper) Am I right? So when a vehicle receives platoon msg, you call onData function and the working responsibility is delegated to lower later. For example, onBeaconVehicle: first ApplVCoordinator::onBeaconVehicle(wsm); is called then based on the platoon depth, VENTOS applies control parameters.

Yes that's right. The application layer code for a vehicle is organized in hierarchy with ApplV_Manager as the last child. The object that will be instantiated from the vehicle class will be of type ApplV_Manager.


2- The scenario that I use is related to the params2_CACC.ini and section 4 where the platoon has already formed. The speed profile of this scenario is set to 3. What are the minimum and maximum speed values of this mode? Is it possible to set min, max, and normal speed? The general parameters ini file contain the speed information. (speed profile). These values are the speed values?

If you go to the VehicleSpeedProfile.cc file in the global folder and check the void SpeedProfile::Change() method you will figure out how the speed profile changes over time. In mode 3 the speed of the first vehicle changes between minSpeed and normalSpeed values. In the config file, we did not specify an explicit value for them so the default value will be used. On the other hand it seems that we did not specify any default value in the ned file!. So I guess yo need to do it yourself.


3-I need a function that gives me the vehicle's front platoon member and rear platoon member. From the Traci_Extend, is there any method that implements this functionality? Or how a platoon member know the front and the rear platoon member in the platoon?

The platooning concept is developed in the omnet side thus SUMO is not aware of it. This means that you can not use TraCI interface to ask this from SUMO. You can simply get the vehicles front platoon member by checking the plnID variable that is defined in ApplV_02_Beacon.h file. If the vehicle is part of a platoon then plnID contains the ID of the platoon leader which is equal to its vehicle ID.

Platoon followers do not keep track of the platoon members, only platoon leader does. This means that a platoon follower does not know what vehicle is behind it. But you can get the following vehicle by looking at the beacon messages. The beacon message coming from the rear vehicle has the same plnID but its depth is one less than the current vehicle.


4- Some parameters in general.ini file and another overlap. For example param4_other adversary and param1_general. Which one do I need to change? I think they override the parameters as in the beginning we include the general parameter file and change on the current file.

If you want to change any parameters, then change it in  param4_other. changing the parameters in param1_general might affect other scenarios too.
