### ISSUE TITLE
Regarding Virtual BOX error

### ISSUE THREAD

**Issue by bargisou** [ManiAm/VENTOS_Public#35]
![ubuntu error](https://user-images.githubusercontent.com/35774990/41476625-c3b1d1ce-70df-11e8-9ffd-7c20a3d84ba8.JPG)

**Comment by ManiAm** [comment]
Dear bargisou,

I am closing this issue, since you are posting a non-related VETNOS problem. Ubuntu-related problems need to be posted in other forums/groups.
