### ISSUE TITLE
Regarding usage of attribute

### ISSUE THREAD

**Issue by bargisou** [ManiAm/VENTOS_Public#36]
Is there any way to address this issue, occurred while using **member index** ::
**'member' is not a valid element in id 'add_6' of addNode.xml file! -- in module (VENTOS::AddNode) Network.addNode (id=7), during network initialization**
I want to use addnode to add multiple class of vehicles at once, member index is what is being used in VENTOS manual but generates some error is it possible to correct this error in any way.

**Comment by bargisou** [comment]
Sir, is the attribute used for vehicles platoon described as  "member"? or is it that the attribute is redefined..?

**Comment by ManiAm** [comment]
It means you can not use the attribute 'member' for adding a vehicle. If you check the manual no attribute called member is defined!

![2018-06-25_8-02-16](https://user-images.githubusercontent.com/5473998/41858207-1e650396-784e-11e8-85f3-e46dfc0daee0.png)

Member is only used in adding a non-homogeneous platoon like this:

![2018-06-25_8-04-36](https://user-images.githubusercontent.com/5473998/41858350-81e3aa4e-784e-11e8-9d33-fdaa317d6fe3.png)

>> I want to use addnode to add multiple class of vehicles at once

Why not using Vehicle Flow? Using the 'typeDist' you can specify multiple vehicle's type. Check the manual for more information.

**Comment by bargisou** [comment]
yes i need a non homogeneous platoon only..so i had added member in add node but it doesn't work...Can i add vehicle flow in addnode file?

**Comment by ManiAm** [comment]
>> so i had added member in add node but it doesn't work

The member attribute, as shown in my last post, takes index and type. Type specifies the vehicle class of that particular member in the platoon.

>> Can i add vehicle flow in addnode file?

You can, but vehicle flow is not a platoon.

If you are looking for a vehicle platoon flow, then unfortunately we have not implemented it yet. If you want to add multiple non-homogeneous platoons, then you need to use vehicle_platoon multiple times.

**Comment by bargisou** [comment]
yes... i want to add multiple non homogeneous platoons but how to use vehicle_platoon multiple times in addnode.xml by defining various types of vehicles in single platoon without using member attribute

**Comment by ManiAm** [comment]
>> i want to add multiple non homogeneous platoons

Why not using something like this in the addNode?
This adds three non-homogeneous platoons plt1, plt2 and plt3, each of size five (I have not tested the code).

```
<vehicle_platoon id="plt1" type="passenger" size="5" route="route0" departLane="0" departPos="200" >
<member index="0" type="emergency" />
<member index="1" type="emergency" />
<member index="2" type="truck" />
</vehicle_platoon>


<vehicle_platoon id="plt2" type="passenger" size="5" route="route0" departLane="0" departPos="400" >
<member index="0" type="emergency" />
<member index="1" type="emergency" />
<member index="2" type="truck" />
</vehicle_platoon>

<vehicle_platoon id="plt3" type="passenger" size="5" route="route0" departLane="0" departPos="600" >
<member index="0" type="emergency" />
<member index="1" type="emergency" />
<member index="2" type="truck" />
</vehicle_platoon>
```

**Comment by bargisou** [comment]
I have tried with member index type, TypeManual and TypeCACC .i will check with above  mentioned code now

**Comment by bargisou** [comment]
along with the addnode code you mentioned above ... what should be added in route file
