### ISSUE TITLE
regarding plotting of matlab scripts using  Speedprofile.m 

### ISSUE THREAD

**Issue by bargisou** [ManiAm/VENTOS_Public#38]
![capture](https://user-images.githubusercontent.com/35774990/41863360-1d235dea-78c4-11e8-8c18-8a3a5f88770f.JPG)

[vehicleData.txt](https://github.com/ManiAm/VENTOS_Public/files/2133928/vehicleData.txt)

using speedprofile.m file and the above vehicledata.txt  file the plot is not being displayed ...above plot getting displayed but graph is not getting uploaded

**Comment by ManiAm** [comment]
I have not tested the script for a while, so you might need to change the script based on your own needs. But looking at your vehicleData.txt, the vehicle speed is very low. That's why the graph is a small dot around zero on the top. Try to zoom-in to the top graph.

**Comment by bargisou** [comment]
[000_vehicleData (1).txt](https://github.com/ManiAm/VENTOS_Public/files/2133961/000_vehicleData.1.txt)


if i upload entire data file following is the error generating   

 reading and parsing the vehData.txt file ...
Subscript indices must either be real positive integers or logicals.

Error in SpeedProfile (line 56)
    vehiclesSpeed(index,vNumber) = speeds(i,1);

**Comment by ManiAm** [comment]
As I mentioned in my last post, the Matlab script assume that a specific sets of columns are present in the txt file. If you look at line 18 and also 22-27, you will see how the columns are interpreted.

https://github.com/ManiAm/VENTOS_Public/blob/master/scripts/SpeedProfile.m

column 1: index
column 2: timestamp
column 3: vehicle
column 4: pos
column 5: speed
column 6: accel

Now go back and look at your txt file. Your txt file has one extra column (frontspacegap).
You need to update line 18 of the matlab script to:

formatSpec = '%d %f %s %f %f %f %f';
 
I have added one more %f to the end.

**Comment by bargisou** [comment]
![capture](https://user-images.githubusercontent.com/35774990/41864577-1e62b5da-78c8-11e8-96c8-aa3b37463dfb.JPG)

Thank you ... its displaying
