### ISSUE TITLE
regarding emission data plotting 

### ISSUE THREAD

**Issue by bargisou** [ManiAm/VENTOS_Public#39]
[000_vehicleEmission.txt](https://github.com/ManiAm/VENTOS_Public/files/2137842/000_vehicleEmission.txt)
like vehicle data is it possible to plot vehicle emission file

**Comment by ManiAm** [comment]
Yes of course! you need to write a new Matlab script to read the columns of the txt file and then plot it. You can get idea from the speedprofile script to get started.
