### ISSUE TITLE
Building VENTOS project in omnet - error refreshing makefiles - both .cc and .cpp files exist

### ISSUE THREAD

**Issue by mosman18** [ManiAm/VENTOS_Public#46]
Hi,
After importing the VENTOS project into OMNET, as described in VENTOS manual page 5, I tried to build the project but I got the following error:

you have both .cc and .cpp files -- specify -e cc or -e cpp option to select which set of files to use

Then the building stops and exists. 
I am kind of a rookie to both VENTOS and OMNET. Can someone please clarify this error and explain to how I can overcome it and build the VENTOS project correctly?

![makefiles error](https://user-images.githubusercontent.com/47752364/52984452-1bcc9400-33b5-11e9-8d25-2657d3655953.jpg)

Thanks

**Comment by ManiAm** [comment]
it should not cause any issues for the main src folder. There exists only two cpp files in the project that reside in the example folder. The makefie never looks into the example folder. Anyhow, thanks for reporting this. changed cpp to cc in the following two instances:

find . -name *.cpp
./examples/router/xmlGen.cpp
./examples/router/sumocfg/grid/xmlGen.cpp
