### ISSUE TITLE
Error building VENTOS_Public project in OMNET SIGINT and SIG_IGN not declared in this scope

### ISSUE THREAD

**Issue by mosman18** [ManiAm/VENTOS_Public#47]
While building VENTOS_Public I encountered the following errors:
Any help how to get past this point would be much appreciated.

![image](https://user-images.githubusercontent.com/47752364/53468086-69cd4180-3a1e-11e9-9e02-8db283e2b856.png)

**Comment by mosman18** [comment]
I am using OMNET 5.4.1 and VM with Ubuntu 18.04--Thank you.

**Comment by PonyCCC** [comment]
> While building VENTOS_Public I encountered the following errors:
> Any help how to get past this point would be much appreciated.
> 
> ![image](https://user-images.githubusercontent.com/47752364/53468086-69cd4180-3a1e-11e9-9e02-8db283e2b856.png)

Its because of missing package
#include <math.h>
#include<signal.h>

**Comment by mosman18** [comment]
Can you please elaborate on your response? Where do I need to insert these 2 missing packages? Do the "math.h" and "signal.h" files already exist and I need to insert the includes somewhere? or Do I need to build them?

Thanks

**Comment by PonyCCC** [comment]
> Can you please elaborate on your response? Where do I need to insert these 2 missing packages? Do the "math.h" and "signal.h" files already exist and I need to insert the includes somewhere? or Do I need to build them?
> 
> Thanks

open the logging/vglog.cc file and insert the package.

**Comment by ManiAm** [comment]
fixed in the latest commit. Thanks for reporting this.
