### ISSUE TITLE
installation fail - always connecting during Omnetpp 5,4 installation

### ISSUE THREAD

**Issue by PonyCCC** [ManiAm/VENTOS_Public#48]
Hi,
when i follow the User Manual and use the runme , but it stop at 
downloading omnet++ version 5.4
cd `...download' [Connecting...]
could you please help me to solve this problem?
Best Regards

**Comment by ManiAm** [comment]
Unfortunately, the FTP server that stores the VENTOS installation files is down at the moment. I am trying to solve the issue when I get more free time.

**Comment by ManiAm** [comment]
fixed in the latest commit. please git pull the latest code in both ventos and ventos_sumo.
