### ISSUE TITLE
How to Install VENTOS in Ubuntu 16.04.01 using OMNET 5.0

### ISSUE THREAD

**Issue by rafeemusabbir** [ManiAm/VENTOS_Public#5]
Hello Mani,
I am one of the PhD student of Dr. Michael. I have a query. How do you Install the VENTOS in Ubuntu 16.04.01 and also with OMNET 5.0.

Thanks in Advance. 
Best,
Rafee

**Comment by ManiAm** [comment]
Hi Rafee,

We will release the latest version on VENTOS early next year and you will have access to the code. Meanwhile I can add you as a collaborator to the private repository.
