### ISSUE TITLE
'simulation' is not defined or declared in the project

### ISSUE THREAD

**Issue by lionkt** [ManiAm/VENTOS_Public#6]
There may be something wrong about the variable `simulation`, like in the `SumoSever.cc`:
> cModul  *module = **simulation**.getSystemModule()->getSubmodule("SumoBinary");

I seached  for the declaration of `simulation` in this repository, but can't find it.

**Comment by ManiAm** [comment]
Are you using OMNET++ 5 to run VENTOS?

OMNET++ 5 introduced namespace and you cannot use the old VENTOS code. You can switch back to OMNET++ 4.6 or wait for a couple of month for the latest release of VENTOS with many new features :)

**Comment by lionkt** [comment]
Thanks for your great job and information!


I'm using OMNET++ 5.0, and I'll try switching back to OMNET++ 4.6 for VENTOS.



――
王冠
单位：清华大学自动化系
手机：18301290210
邮编：100084

Wang Guan
Department of Automation, Tsinghua University, Beijing, 100084
Mobile Phone: 18301290210




________________________________
发件人: Mani Amoozadeh <notifications@github.com>
发送时间: 2017年2月25日 1:08
收件人: ManiAm/VENTOS_Public
抄送: lionkt; Author
主题: Re: [ManiAm/VENTOS_Public] 'simulation' is not defined or declared in the project (#6)


Are you using OMNET++ 5 to run VENTOS?

OMNET++ 5 introduced namespace and you cannot use the old VENTOS code. You can switch back to OMNET++ 4.6 or wait for a couple of month for the latest release of VENTOS with many new features :)

―

**Comment by lionkt** [comment]
Thanks for your great job and information! 
I'm using OMNET++ 5.0, and I'll try switching back to OMNET++ 4.6 for VENTOS

**Comment by ManiAm** [comment]
I hope your issue is resolved now. I am closing this issue.
