### ISSUE TITLE
VENTOS user manual

### ISSUE THREAD

**Issue by weixun20124420** [ManiAm/VENTOS_Public#8]
Excuse me, what's the VENTOS user manual unable to download? @ManiAm

**Comment by ManiAm** [comment]
Hi Weixun,

I have updated the VENTOS website and fixed the link to the manual. Don't forget to get the latest VENTOS code as we just released it.

**Comment by weixun20124420** [comment]
Hi ManiAm,
I have downloaded the manuals and the latest VENTOS code. Thank you very much! I have some other issues, may I  install VENTOS on Ubuntu 16.04.2 LTS and software version of OMNET++ should I choose 4.6 or 5.1? And what is the requirement for the software version of SUMO?  I've been using Windows in PC before, and I haven't used Linux. I hope you can give me some advice.

**Comment by ManiAm** [comment]
You can install Ubuntu 16.04 on a virtual machine (such as virtual box or VM Ware). Then clone the VENTOS repository and run the 'runme' script. It will download omnet, sumo, etc automatically. Check the installation section in the manual.

**Comment by weixun20124420** [comment]
I will try.Thank you very much for your kind help!
