### ISSUE TITLE
Can't find certificate in keychain access

### ISSUE THREAD

**Issue by Liefersar** [ManiAm/VENTOS_Public#9]
I'm trying to install VENTOS on macOS High Sierra (10.13.1).

During installation I get this notification:
>Check gdb
=========
 /usr/local/bin/gdb
gdb found in /usr/local/bin/gdb
gdb is not signed!
certificate VENTOS already exists!

I followed the instructions for changing the trust of the certificate but VENTOS is not shown in my keychain access.

Any help?

**Comment by ManiAm** [comment]
Hello Liefersar,

The certificate is used in order to make gdb working. If you do not use gdb then you can skip those line. We have known issues in Mac. I suggest you (for now) to use Ubuntu 16 (probably in a virtual machine).
